#!/bin/bash
#
# InfraHouse cloud-init bootstrap script.
#
# Runs under `set -euo pipefail` so any failing step aborts bootstrap and
# surfaces in /var/log/cloud-init-output.log instead of being silently
# swallowed by cloud-init's runcmd module. /var/run/puppet-done is written
# only on the success path, so it is a truthful "bootstrap complete" marker.
#
# This file is generated by terraform-aws-cloud-init via templatefile().
#
set -euo pipefail

%{ if lifecycle_hook_name != "" ~}
_ih_signal_abandon() {
    set +e
    ih-aws --verbose autoscaling complete "${lifecycle_hook_name}" --result ABANDON
    exit 1
}
trap _ih_signal_abandon ERR
%{ endif ~}

%{ if mount_volumes ~}
mount -a
%{ endif ~}

PATH=/opt/puppetlabs/puppet/bin:$PATH gem install json
PATH=/opt/puppetlabs/puppet/bin:$PATH gem install aws-sdk-core
PATH=/opt/puppetlabs/puppet/bin:$PATH gem install aws-sdk-secretsmanager

%{ for cmd in pre_runcmd ~}
${cmd}
%{ endfor ~}

${puppet_cmd}

%{ for cmd in post_runcmd ~}
${cmd}
%{ endfor ~}

touch /var/run/puppet-done

%{ if lifecycle_hook_name != "" ~}
ih-aws --verbose autoscaling complete "${lifecycle_hook_name}" --result CONTINUE
%{ endif ~}
